version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DEBUG=1
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=artixcorejango
      - MYSQL_ROOT_PASSWORD=artixcore

volumes:
  mysql_data:
