# Generated by Django 5.0.1 on 2024-01-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_send_count',
            field=models.IntegerField(default=0),
        ),
    ]
