# Generated by Django 5.0.1 on 2024-01-05 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_frontendcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
