# Generated by Django 5.0.1 on 2024-01-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_customuser_email_verification_send_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('supreme_admin', 'Supreme Admin'), ('admin', 'Admin'), ('content_writer_admin', 'Content Writer Admin'), ('content_writer', 'Content Writer'), ('ad_manager_admin', 'Ad Manager Admin'), ('ad_manager', 'Ad Manager'), ('accountant_admin', 'Accountant Admin'), ('accountant', 'Accountant'), ('hr_admin', 'HR Admin'), ('hr', 'HR'), ('developer_admin', 'Developer Admin'), ('developer', 'Developer'), ('data_scientist_admin', 'Data Scientist Admin'), ('data_scientist', 'Data Scientist'), ('blogger_admin', 'Blogger Admin'), ('blogger', 'Blogger'), ('designer_admin', 'Designer Admin'), ('designer', 'Designer'), ('general_user', 'General User')], default='general_user', max_length=20),
        ),
    ]
