# Generated by Django 5.0.1 on 2024-01-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_frontendcontent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendcontent',
            name='content_type',
            field=models.CharField(choices=[('hero_section', 'Hero Section'), ('about_section', 'About Section'), ('services_section', 'Services Section'), ('blog_section', 'Blog Section'), ('projects_section', 'Projects Section'), ('protfolio_section', 'Protfolio Section'), ('reviews_section', 'Reviews Section'), ('pricing_section', 'Pricing Section'), ('team_section', 'Team Section'), ('contact_section', 'Contact Section'), ('social_links', 'Social Links'), ('footer_section', 'Footer Section')], max_length=20),
        ),
        migrations.AlterField(
            model_name='frontendcontent',
            name='title_type',
            field=models.CharField(choices=[('main_content', 'Main Content'), ('sub_content', 'Sub Content')], max_length=20),
        ),
    ]
