# Generated by Django 5.0.1 on 2024-02-13 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_menu_menucontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucontent',
            name='menu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.menu', unique=True),
        ),
    ]
