# Generated by Django 5.0.1 on 2024-02-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_alter_menu_menu_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucontent',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
