# Generated by Django 5.0.1 on 2024-03-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_alter_menucontent_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontendcontent',
            name='title_type',
        ),
        migrations.AlterField(
            model_name='frontendcontent',
            name='content_type',
            field=models.CharField(max_length=50),
        ),
    ]
