# Generated by Django 5.0.1 on 2024-03-11 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_remove_menucontent_menu_id_menucontent_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucontent',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menucontent', to='admin_app.menu'),
        ),
    ]
